In [2]:
list=[2,3,4,5,6,7,88,44,22]

print(list)
type(list)

[2, 3, 4, 5, 6, 7, 88, 44, 22]


list

In [3]:
list.remove(44)

In [4]:
list

[2, 3, 4, 5, 6, 7, 88, 22]

In [5]:
list.append(100)

In [6]:
list

[2, 3, 4, 5, 6, 7, 88, 22, 100]

In [17]:
# list.pop()
print(list)
list.reverse()
print(list)
list.index(4)

[6, 5, 4, 3]
[3, 4, 5, 6]


1

In [19]:
list.append(102)
list.append(188)
list.append(666)
list

[3, 4, 5, 6, 102, 102, 188, 666]

In [23]:
list.append(10)
list.append(3)
list

[3, 4, 5, 6, 102, 102, 188, 666, 10, 3]

In [24]:
list.sort()
print(list)

[3, 3, 4, 5, 6, 10, 102, 102, 188, 666]


In [25]:
del list[2:4]
print(list)

[3, 3, 6, 10, 102, 102, 188, 666]


In [31]:
#to concatenate the string in print statement
# del list[3]
print("List is "+str(list))
list[:]

List is [3, 3, 6, 188, 666]


[3, 3, 6, 188, 666]

In [38]:
list[::-1]

[666, 188, 6, 3, 3]

In [51]:
sec=[1,4,5,7,6,8,9,11,23,44,55,77,88,99]
len(sec)
print(sec[0:10:4])
print(sec[::2])

[1, 6, 23]
[1, 5, 6, 9, 23, 55, 88]


In [55]:
print(sec[2:-3])

[5, 7, 6, 8, 9, 11, 23, 44, 55]


In [56]:
print(sec)

[1, 4, 5, 7, 6, 8, 9, 11, 23, 44, 55, 77, 88, 99]


In [57]:
print(sec[::-1])

[99, 88, 77, 55, 44, 23, 11, 9, 8, 6, 7, 5, 4, 1]


In [69]:
print(len(sec))
print(sec[0:10:3])
print(sec[:])
print(sec[5:10])

14
[1, 7, 9, 44]
[1, 4, 5, 7, 6, 8, 9, 11, 23, 44, 55, 77, 88, 99]
[]


In [78]:
import numpy as np
array=[2,3,4,6,7,9,11,23,44,55,66,76]
a=np.asarray(array)

In [79]:
type(a)

numpy.ndarray

In [82]:
a=a*100
print(a)

[10200 10300 10400 10600 10700 10900 11100 12300 14400 15500 16600 17600]


In [89]:
b=[10,20,30]
numAr=np.array(b)
np.dot(numAr,numAr)
#np.dot()  10*10 +20*20 +30*30 ==1400

1400

In [2]:
import numpy as np
array=[[1,2,3,4],
       [2,3,4,5]]
npar=np.array(array)
npar.shape

(2, 4)

In [9]:
npar=npar.reshape(4,2)
print(type(npar))
print(npar)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [2 3]
 [4 5]]


In [12]:
npar[1,0]

3

In [18]:
ray=[[1,2,3,4,5,6,7,8,9,10],
             [11,12,13,14,15,16,17,18,19,20]]
np_array=np.array(ray)
print(np_array[1,0:5]) 
#  //means ist row and elements from 0 to 5 index

[11 12 13 14 15]


In [20]:
np_array[0,::-1]
#reverse and array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.sum())
# print(np_array.median())

print(np_array.var())

print(np_array.std())


20
1
10.5
210
33.25
5.766281297335398


In [31]:
matrix=[[1,2],
        [3,4],
        [5,6],
        [7,8]]
np_mat=np.array(matrix)
print(np_mat.sum(axis=0))
print(np_mat.sum(axis=1))
print(np_mat.sum(axis=None))


[16 20]
[ 3  7 11 15]
36


In [33]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])
np.concatenate((array_1,array_2,array_3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
array_4 = np.array([[1,2,3],[0,0,0]])
array_5 = np.array([[0,0,0],[7,8,9]])
np.concatenate((array_4,array_5),axis=0)
np.concatenate((array_4,array_5),axis=1)


array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 7, 8, 9]])

In [46]:
z=np.zeros((3,8),dtype=np.int)
z.dtype

dtype('int64')

In [42]:
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [47]:
z=np.ones((3,8),dtype=np.int)
z.dtype

dtype('int64')

In [48]:
print(z)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [53]:
print(np.identity(8))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [60]:
print(np.eye(8,8,k=-2))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


In [62]:
ar6=np.array([1,2])
ar7=np.array([3,4])
print(np.dot(ar6,ar7))
print(np.cross(ar6,ar7))

11
-2
